// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDockerStatus():Promise<void>;

export function GetPeers():Promise<Array<main.PeerInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ListServices():Promise<Array<main.Service>>;

export function StartService(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopService(arg1:string):Promise<string>;
