// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDockerStatus() {
  return window['go']['main']['App']['CheckDockerStatus']();
}

export function GetNodeSnapshot() {
  return window['go']['main']['App']['GetNodeSnapshot']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListRecommendedServices() {
  return window['go']['main']['App']['ListRecommendedServices']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function StartService(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartService'](arg1, arg2, arg3);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
