// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastServices() {
  return window['go']['main']['ServiceNode']['BroadcastServices']();
}

export function GetPeers() {
  return window['go']['main']['ServiceNode']['GetPeers']();
}

export function InitP2P() {
  return window['go']['main']['ServiceNode']['InitP2P']();
}

export function ListServices() {
  return window['go']['main']['ServiceNode']['ListServices']();
}

export function StartService(arg1, arg2, arg3) {
  return window['go']['main']['ServiceNode']['StartService'](arg1, arg2, arg3);
}

export function StopService(arg1) {
  return window['go']['main']['ServiceNode']['StopService'](arg1);
}
